# Generated by Django 3.2.4 on 2021-07-08 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='category',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='noticias',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('featured', models.BooleanField(default=False, max_length=300)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_proyecto.cliente')),
                ('noticias', models.ManyToManyField(to='app_proyecto.Noticias')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categories',
                'ordering': ['-id'],
            },
        ),
    ]
